version: '3.8'

services:
  app1:
    container_name: api-server
    build:
      context: ./public.api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app1db
      - SPRING_DATASOURCE_USERNAME=app1user
      - SPRING_DATASOURCE_PASSWORD=app1password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
    networks:
      - app-network

  app2:
    container_name: 3p-retriever
    build:
      context: ./retriever.svc
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/app2db
      - SPRING_DATASOURCE_USERNAME=app2user
      - SPRING_DATASOURCE_PASSWORD=app2password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: shared_db
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
